id: P007900
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4801
  title: མདོ་སྡེ་ལས་བརྒྱ་པ།
  author: ''
  volumes:
    f09cffda69704c3f840faf9556cd17d5:
      image_group_id: I3CN4803
      title: Volume 1 of mdo sde las brgya pa/
      volume_number: 1
      total_pages: 744
      base_file: v001.txt
ebook_metadata:
  title: མདོ་སྡེ་ལས་བརྒྱ་པ།
  author: ''
  sku: P007900
  cover: cover.jpg
  layers:
  - pagination
