id: P007900
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:48:05.811501
source_metadata:
  id: bdr:W3CN4801
  title: མདོ་སྡེ་ལས་བརྒྱ་པ།
  author: ''
  volumes:
    f09cffda69704c3f840faf9556cd17d5:
      image_group_id: I3CN4803
      title: Volume 1 of mdo sde las brgya pa/
      volume_number: 1
      total_pages: 744
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
