id: P007900
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4801
  title: མདོ་སྡེ་ལས་བརྒྱ་པ།
  author: ''
  volumes:
    0612ff25a3a443ae85fcf4660b70e1fe:
      image_group_id: I3CN4803
      title: ''
      volume_number: 1
      total_pages: 744
ebook_metadata:
  title: མདོ་སྡེ་ལས་བརྒྱ་པ།
  author: ''
  sku: P007900
  cover: cover.jpg
  layers:
  - pagination
