id: I194A999A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:50:30+00:00'
last_modified: '2022-06-09T07:14:45.475833+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4801
  title: མདོ་སྡེ་ལས་བརྒྱ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    29D8:
      image_group_id: I3CN4803
      title: Volume 1 of mdo sde las brgya pa/
      total_pages: 744
      order: 1
      base_file: 29D8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
